---
- name: Create TFTP directory
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
    mode: '0755'

- name: set up pxelinux
  template:
    src: default
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    owner: root
    group: root
    mode: 0755

- name: copy files to TFTP share
  copy:
    src: /usr/share/syslinux/
    dest: /var/lib/tftpboot/
    mode: '0755'
    remote_src: true

- name: copy initrd and vmlinuz files to TFTP share
  copy:
    src: /var/www/centos7/isolinux/
    dest: /var/lib/tftpboot/
    mode: '0755'
    remote_src: true

- name: restart tftp-server
  service:
    name: tftp.service
    state: restarted
    enabled: true
